### ISSUE TITLE
how to install together the usual 8266 lib

### ISSUE THREAD

**Issue by aldolo69** [uli/Arduino_nowifi#1]
this lib is exactly what i was lookig for but it is not clear to me how to use it. you included the original readme but i already have the 8266 lib installed. it is possible to use this nowifi lib side by side with the usual 8266 lib?

**Comment by uli** [comment]
Yes, it is. If you have, say, a directory `hardware/esp8266com/esp8266`, you can put this core in `hardware/esp8266com/esp8266_nowifi`, and it should work.

**Comment by aldolo69** [comment]
great! now i've got 78k free ram. i've created a "hardware" subfolder in the same folder used by sketch, an "esp8266com" subfolder and then extracted the whole zip there.

documents\arduino\hardware\esp8266com\.....
