### ISSUE TITLE
millis() wraps too early

### ISSUE THREAD

**Issue by konimaru** [uli/Arduino_nowifi#4]
**TICK(0)** simply returns **millis()** (ms since power-on). The issue here is that the latter wraps after 1.19h because for some reason the timer handler (**micros_overflow_tick**) dealing with overflows doesn't do its job (see ./tools/esp8266/arduino-1.8.5/hardware/esp8266com/esp8266_nowifi/cores/esp8266/core_esp8266_wiring.c). Expected overflow here - assuming we stay in sync with arduino & Co - is after 49.71d.

As a side-effect, **millis()** not using the full 32bit range breaks commands like **WAIT** in interesting ways (including complete lock-up).

**Comment by uli** [comment]
The nowifi fork disables the entire OS stuff, so the handler is never called.

I have pushed what I hope to be a fix to the overflow_fix branch here. It is compile-tested only as I don't have access to hardware right now. Please check if it works for you, then I'll merge it into the main branch.

**Comment by konimaru** [comment]
Ok, now the handling is all done in **millis()**. Question now is, how do we guarantee that this function is called often enough, e.g. if it's called only after 2 hours then the value will still be wrong. Unless there is some place (in the interpreter) I overlooked.

I'm also a bit uneasy about 4294967. I have the feeling it should be 4294968 ...

**Comment by konimaru** [comment]
We could do a dummy call every 4096th vsync which is similar to the original 60sec.

**Comment by uli** [comment]
174efe379d4 fixes the overflow issue. I do not think that the inaccuracies introduced in the overflow handling are really worth the effort required to fix them.
